

http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
xpack.monitoring.elasticsearch.hosts: [ "opendistro-es:9200" ]
xpack.monitoring.elasticsearch.username: "admin"
xpack.monitoring.elasticsearch.password: "admin"